#!/usr/bin/env bash
set -euo pipefail

LOGFILE="ci/logs/build.log"
mkdir -p ci/logs
echo "$(date -Iseconds) Starting unified build..." | tee -a "$LOGFILE"

# --- 1. Генерация manifest.json ---
echo "📌 Step 1: Detect project and generate manifest.json"
bash ci/ci-scripts/detect-entry.sh

MANIFEST="manifest.json"
if [ ! -f "$MANIFEST" ]; then
  echo "❌ Manifest not found! Exiting." | tee -a "$LOGFILE"
  exit 1
fi

LANGUAGE=$(jq -r '.language' "$MANIFEST")
HAS_DOCKERFILE=$(jq -r '.has_dockerfile' "$MANIFEST")
ENTRY=$(jq -r '.entry // empty' "$MANIFEST")
DEPS_FILE=$(jq -r '.deps_file // empty' "$MANIFEST")
DATABASE=$(jq -r '.database // "unknown-database"' "$MANIFEST")
PROJECT_DIR=$(dirname "$MANIFEST")
IMAGE_NAME=${1:-auto-project:latest}

echo "📦 Language: $LANGUAGE" | tee -a "$LOGFILE"
echo "📄 Dockerfile present: $HAS_DOCKERFILE" | tee -a "$LOGFILE"
echo "➡️  Entry: $ENTRY" | tee -a "$LOGFILE"
[ -n "$DEPS_FILE" ] && echo "📦 Deps file: $DEPS_FILE" | tee -a "$LOGFILE"
echo "📂 Project dir: $PROJECT_DIR" | tee -a "$LOGFILE"
echo "🗄 Database: $DATABASE" | tee -a "$LOGFILE"

# --- 2. Подъём БД (если указана) ---
DB_CONTAINER=""
if [[ "$DATABASE" == "postgres" ]]; then
    echo "🟢 Starting temporary PostgreSQL container..."
    DB_CONTAINER=$(docker run -d -e POSTGRES_PASSWORD=ci -p 5432:5432 postgres:15)
    echo "Postgres container: $DB_CONTAINER"
elif [[ "$DATABASE" == "mysql" ]]; then
    echo "🟢 Starting temporary MySQL container..."
    DB_CONTAINER=$(docker run -d -e MYSQL_ROOT_PASSWORD=ci -p 3306:3306 mysql:8)
    echo "MySQL container: $DB_CONTAINER"
else
    echo "⚪ No database container will be started."
fi

# --- 3. Генерация или использование Dockerfile ---
DOCKERFILE_PATH="$PROJECT_DIR/Dockerfile"
if [[ "$HAS_DOCKERFILE" != "true" || ! -f "$DOCKERFILE_PATH" ]]; then
    echo "⚙️ Generating temporary Dockerfile for $LANGUAGE..."
    DOCKERFILE_PATH="$PROJECT_DIR/Dockerfile.ci"
    cat > "$DOCKERFILE_PATH" <<'EOF'
# Temporary Dockerfile generated by build.sh
EOF

    case "$LANGUAGE" in
        python)
            cat >> "$DOCKERFILE_PATH" <<EOF
FROM python:3.11
WORKDIR /
COPY . /
ENV PYTHONUNBUFFERED=1
RUN python -m pip install --upgrade pip
EOF
            if [ -n "$DEPS_FILE" ]; then
                cat >> "$DOCKERFILE_PATH" <<EOF
RUN pip install -r "$DEPS_FILE"
EOF
            fi
            cat >> "$DOCKERFILE_PATH" <<EOF
CMD ["python", "$ENTRY"]
EOF
            ;;
        go)
            cat >> "$DOCKERFILE_PATH" <<EOF
FROM golang:1.20-alpine AS build
WORKDIR /src
COPY . .
RUN apk add --no-cache build-base git
WORKDIR /src/project
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/app ./...
FROM alpine:3.18
COPY --from=build /out/app /usr/local/bin/app
ENTRYPOINT ["/usr/local/bin/app"]
EOF
            ;;
        cpp)
            cat >> "$DOCKERFILE_PATH" <<EOF
FROM ubuntu:24.04 AS builder
WORKDIR /src
RUN apt-get update && apt-get install -y --no-install-recommends build-essential cmake git pkg-config ca-certificates file && rm -rf /var/lib/apt/lists/*
COPY . .
RUN mkdir -p build && cd build && cmake /src/project && cmake --build . -j\$(nproc)
RUN BIN=\$(find build -type f -executable -exec file {} \; | grep ELF | cut -d: -f1 | head -n1) && cp "\$BIN" /usr/local/bin/app
FROM ubuntu:24.04
COPY --from=builder /usr/local/bin/app /usr/local/bin/app
CMD ["/usr/local/bin/app"]
EOF
            ;;
        *)
            cat >> "$DOCKERFILE_PATH" <<EOF
FROM alpine:3.18
COPY . .
CMD ["sh", "-c", "ls -la && echo 'No start command defined'"]
EOF
            ;;
    esac
else
    echo "✅ Using existing Dockerfile at $DOCKERFILE_PATH"
fi

# --- 4. Build Docker image ---
echo "🚀 Building Docker image $IMAGE_NAME..."
docker build -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" "$PROJECT_DIR"

# --- 5. Cleanup ---
if [[ "$DOCKERFILE_PATH" == "$PROJECT_DIR/Dockerfile.ci" ]]; then
    rm -f "$DOCKERFILE_PATH"
fi

if [ -n "$DB_CONTAINER" ]; then
    echo "🧹 Stopping temporary DB container..."
    docker rm -f "$DB_CONTAINER"
fi

echo "✅ Build finished. Image: $IMAGE_NAME"
