#!/usr/bin/env bash
set -euo pipefail

MANIFEST=${1:-project/manifest.json}
IMAGE_NAME=${2:-myorg/myapp:latest}    # можно переопределить аргументом
PUSH=${3:-false}                       # true|false
LOAD_LOCAL=${4:-false}                 # true|false (если нужно --load вместо push)
BUILDX=${5:-true}                      # use buildx by default

if ! command -v jq >/dev/null 2>&1; then
  echo "❌ Require jq installed" >&2
  exit 2
fi

if [ ! -f "$MANIFEST" ]; then
  echo "❌ Manifest not found: $MANIFEST" >&2
  exit 2
fi

# читаем manifest
LANGUAGE=$(jq -r '.language // "unknown"' "$MANIFEST")
HAS_DOCKERFILE=$(jq -r '.has_dockerfile // false' "$MANIFEST")
ENTRY=$(jq -r '.entry // empty' "$MANIFEST")
TARGETS=$(jq -r '.targets | join(",") // "linux/amd64"' "$MANIFEST")
PROJECT_DIR=$(dirname "$MANIFEST")

echo "📦 Language: $LANGUAGE"
echo "📄 Dockerfile present: $HAS_DOCKERFILE"
echo "➡️  Entry (raw): $ENTRY"
echo "📂 Project dir: $PROJECT_DIR"
echo "🎯 Targets: $TARGETS"

# ensure project dir exists
if [ ! -d "$PROJECT_DIR" ]; then
  echo "❌ Project directory not found: $PROJECT_DIR" >&2
  exit 2
fi

# normalize ENTRY relative to project dir
if [ -n "$ENTRY" ]; then
  ENTRY_REL=$(realpath --relative-to="$PROJECT_DIR" "$ENTRY" 2>/dev/null || echo "$ENTRY")
else
  ENTRY_REL=""
fi
echo "➡️  ENTRY relative: $ENTRY_REL"

# Если проект сам содержит Dockerfile
if [ "$HAS_DOCKERFILE" = "true" ] && [ -f "$PROJECT_DIR/Dockerfile" ]; then
  echo "✅ Using project's Dockerfile: $PROJECT_DIR/Dockerfile"
  DOCKERFILE_PATH="$PROJECT_DIR/Dockerfile"
else
  echo "⚙️  No Dockerfile -> generating temporary Dockerfile.ci for language=$LANGUAGE"
  DOCKERFILE_PATH="$PROJECT_DIR/Dockerfile.ci"

  cat > "$DOCKERFILE_PATH" <<'EOF'
# Temporary Dockerfile generated by build.sh
EOF

  case "$LANGUAGE" in
    python)
      cat >> "$DOCKERFILE_PATH" <<EOF
FROM python:3.11-slim
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -r requirements.txt || true
EOF
      if [ -n "$ENTRY_REL" ]; then
        echo "CMD [\"python\", \"./$ENTRY_REL\"]" >> "$DOCKERFILE_PATH"
      else
        echo "CMD [\"sh\", \"-c\", \"ls -la /app\"]" >> "$DOCKERFILE_PATH"
      fi
      ;;
    go)
      cat >> "$DOCKERFILE_PATH" <<EOF
FROM golang:1.20-alpine AS build
WORKDIR /app
COPY . .
RUN apk add --no-cache build-base git && go mod tidy && go build -o app .

FROM alpine:3.18
WORKDIR /app
COPY --from=build /app/app .
ENTRYPOINT ["./app"]
EOF
      ;;
    cpp|c++)
      cat >> "$DOCKERFILE_PATH" <<EOF
FROM debian:bookworm-slim AS build

# Устанавливаем инструменты для сборки
RUN apt-get update && apt-get install -y g++ cmake make

WORKDIR /app
COPY . .

# Собираем проект через CMake
WORKDIR /app/project/test
RUN mkdir -p build && cd build && cmake .. && make -j4

# Runtime образ
FROM debian:bookworm-slim
WORKDIR /app
COPY --from=build /app/project/test/build/test ./test
ENTRYPOINT ["./test"]

EOF
      ;;
    rust)
      cat >> "$DOCKERFILE_PATH" <<EOF
FROM rust:1.72 AS build
WORKDIR /app
COPY . .
RUN cargo build --release
FROM debian:bookworm-slim
WORKDIR /app
COPY --from=build /app/target/release/* /usr/local/bin/
CMD ["sh", "-c", "ls -la /usr/local/bin && echo 'Run your binary here'"]
EOF
      ;;
    node)
      cat >> "$DOCKERFILE_PATH" <<EOF
FROM node:18-alpine
WORKDIR /app
COPY package*.json . || true
RUN npm install || true
COPY . .
EOF
      if [ -n "$ENTRY_REL" ]; then
        echo "CMD [\"node\", \"./$ENTRY_REL\"]" >> "$DOCKERFILE_PATH"
      else
        echo "CMD [\"npm\", \"start\"]" >> "$DOCKERFILE_PATH"
      fi
      ;;
    *)
      echo "⚠️  Language $LANGUAGE not recognized; using generic Alpine image"
      cat >> "$DOCKERFILE_PATH" <<EOF
FROM alpine:3.18
WORKDIR /app
COPY . .
CMD ["sh", "-c", "ls -la && echo 'No start command defined'"]
EOF
      ;;
  esac
fi

# Build image
PLATFORMS="$TARGETS"

if [ "$BUILDX" = "true" ]; then
  docker buildx inspect >/dev/null 2>&1 || docker buildx create --use
  if [ "$PUSH" = "true" ]; then
    docker buildx build --platform "$PLATFORMS" -t "$IMAGE_NAME" --push -f "$DOCKERFILE_PATH" "$PROJECT_DIR"
  else
    if [ "$LOAD_LOCAL" = "true" ]; then
      docker buildx build --platform "$PLATFORMS" -t "$IMAGE_NAME" --load -f "$DOCKERFILE_PATH" "$PROJECT_DIR"
    else
      docker buildx build --platform "$PLATFORMS" -t "$IMAGE_NAME" -f "$DOCKERFILE_PATH" "$PROJECT_DIR"
    fi
  fi
else
  docker build -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" "$PROJECT_DIR"
  if [ "$PUSH" = "true" ]; then
    docker push "$IMAGE_NAME"
  fi
fi

# Clean up
if [ "$DOCKERFILE_PATH" = "$PROJECT_DIR/Dockerfile.ci" ]; then
  rm -f "$DOCKERFILE_PATH"
fi

echo "✅ Done. Built $IMAGE_NAME"
