#!/usr/bin/env bash
set -euo pipefail

MANIFEST=${1:-project/manifest.json}
IMAGE_NAME=${2:-myorg/myapp:latest}    # можно переопределить аргументом
PUSH=${3:-false}                       # true|false
LOAD_LOCAL=${4:-false}                 # true|false (если нужно --load вместо push)
BUILDX=${5:-true}                      # use buildx by default

if ! command -v jq >/dev/null 2>&1; then
  echo "❌ Require jq installed" >&2
  exit 2
fi

if [ ! -f "$MANIFEST" ]; then
  echo "❌ Manifest not found: $MANIFEST" >&2
  exit 2
fi

# читаем manifest
LANGUAGE=$(jq -r '.language // "unknown"' "$MANIFEST")
HAS_DOCKERFILE=$(jq -r '.has_dockerfile // false' "$MANIFEST")
ENTRY=$(jq -r '.entry // empty' "$MANIFEST")
TARGETS=$(jq -r '.targets | join(",") // "linux/amd64"' "$MANIFEST")
PROJECT_DIR=$(dirname "$MANIFEST")   # ожидаем manifest в project/manifest.json

echo "📦 Language: $LANGUAGE"
echo "📄 Dockerfile present: $HAS_DOCKERFILE"
echo "➡️  Entry: $ENTRY"
echo "📂 Project dir: $PROJECT_DIR"
echo "🎯 Targets: $TARGETS"

# ensure project dir exists
if [ ! -d "$PROJECT_DIR" ]; then
  echo "❌ Project directory not found: $PROJECT_DIR" >&2
  exit 2
fi

# Если проект сам содержит Dockerfile
if [ "$HAS_DOCKERFILE" = "true" ] && [ -f "$PROJECT_DIR/Dockerfile" ]; then
  echo "✅ Using project's Dockerfile: $PROJECT_DIR/Dockerfile"
  DOCKERFILE_PATH="$PROJECT_DIR/Dockerfile"
else
  echo "⚙️  No Dockerfile -> generating temporary Dockerfile.ci for language=$LANGUAGE"
  DOCKERFILE_PATH="$PROJECT_DIR/Dockerfile.ci"

  cat > "$DOCKERFILE_PATH" <<'EOF'
# Temporary Dockerfile generated by ci/ci-scripts/build.sh
EOF

  case "$LANGUAGE" in
    go)
      cat >> "$DOCKERFILE_PATH" <<'EOF'
FROM golang:1.20-alpine AS build
WORKDIR /src
COPY . .
RUN apk add --no-cache build-base git && \
    go mod download && \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/app ./...

FROM alpine:3.18
RUN adduser -D appuser
COPY --from=build /out/app /usr/local/bin/app
USER appuser
ENTRYPOINT ["/usr/local/bin/app"]
EOF
      ;;
    python)
      cat >> "$DOCKERFILE_PATH" <<'EOF'
FROM python:3.11-slim AS build
WORKDIR /app
COPY requirements.txt . || true
RUN python -m pip install --upgrade pip
RUN if [ -f requirements.txt ]; then pip wheel -r requirements.txt --wheel-dir=/wheels || true; fi

FROM python:3.11-slim AS runtime
WORKDIR /app
COPY . .
RUN if [ -d /wheels ]; then pip install --no-index --find-links=/wheels -r requirements.txt || true; fi
CMD ["sh", "-c", "python ${ENTRY}"]
EOF
      ;;
    node)
      cat >> "$DOCKERFILE_PATH" <<'EOF'
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json . || true
RUN if [ -f package-lock.json ]; then npm ci; elif [ -f yarn.lock ]; then yarn install; else npm install; fi || true
COPY . .
RUN if [ -f package.json ] && jq -e '.scripts.build' package.json >/dev/null 2>&1; then npm run build || true; fi

FROM node:18-alpine AS runtime
WORKDIR /app
COPY --from=build /app . 
ENV NODE_ENV=production
CMD ["sh", "-c", "node ${ENTRY}"]
EOF
      ;;
    java)
      cat >> "$DOCKERFILE_PATH" <<'EOF'
FROM maven:3.8.8-eclipse-temurin-17 AS build
WORKDIR /build
COPY pom.xml . || true
COPY src ./src
RUN mvn -B package -DskipTests || true

FROM eclipse-temurin:17-jre-jammy AS run
WORKDIR /app
COPY --from=build /build/target/*.jar ./app.jar
CMD ["java", "-jar", "/app/app.jar"]
EOF
      ;;
    rust)
      cat >> "$DOCKERFILE_PATH" <<'EOF'
FROM rust:1.72 AS builder
WORKDIR /usr/src/app
COPY Cargo.toml Cargo.lock . || true
RUN mkdir src && echo "fn main(){}" > src/main.rs
RUN cargo build --release || true
COPY . .
RUN cargo build --release
FROM debian:bookworm-slim
COPY --from=builder /usr/src/app/target/release/* /usr/local/bin/
CMD ["sh", "-c", "/usr/local/bin/$(basename ${ENTRY} .rs)"]
EOF
      ;;
    dotnet)
      cat >> "$DOCKERFILE_PATH" <<'EOF'
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY *.csproj . || true
RUN dotnet restore || true
COPY . . 
RUN dotnet publish -c Release -o /app || true

FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "YourApp.dll"]
EOF
      ;;
    cpp)
      cat >> "$DOCKERFILE_PATH" <<'EOF'
# Build stage for C++ (CMake)
FROM ubuntu:24.04 AS builder
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /src

# install build deps
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential cmake git pkg-config ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY . .

# ensure possible dirs exist so COPY from builder won't fail
RUN mkdir -p build example bench

# (Optional) try to compile an explicit provided .cpp later (generator may insert a compile step)
# configure & build (attempt; don't fail whole build if project has no executable)
RUN mkdir -p build && cd build && cmake .. && make -j$(nproc) || true

# runtime stage
FROM ubuntu:24.04 AS runtime
WORKDIR /app

# create non-root user
RUN adduser --disabled-password --gecos "" appuser || true

# prepare runtime bin dir
RUN mkdir -p /usr/local/bin

# copy potential build outputs from builder (directories guaranteed to exist)
COPY --from=builder /src/build /tmp/build
COPY --from=builder /src/example /tmp/example
COPY --from=builder /src/bench /tmp/bench

# find executables and copy them into /usr/local/bin
RUN set -eux; \
    for d in /tmp/build /tmp/example /tmp/bench; do \
      if [ -d "$d" ]; then \
        find "$d" -type f -executable -exec cp {} /usr/local/bin/ \; || true; \
      fi; \
    done; \
    ls -la /usr/local/bin || true

# create entrypoint script
RUN cat > /usr/local/bin/ci-entrypoint.sh <<'SH'
#!/bin/sh
set -e
if [ -n "${ENTRY}" ]; then
  exec sh -c "${ENTRY}"
fi
BIN=$(ls /usr/local/bin | head -n1 || true)
if [ -n "$BIN" ]; then
  exec /usr/local/bin/"$BIN"
else
  echo "No executable found in image"
  sleep infinity
fi
SH
RUN chmod +x /usr/local/bin/ci-entrypoint.sh

CMD ["/usr/local/bin/ci-entrypoint.sh"]
EOF
      ;;
    *)
      echo "⚠️  Language $LANGUAGE not recognized; generating generic image"
      cat >> "$DOCKERFILE_PATH" <<'EOF'
FROM alpine:3.18
WORKDIR /app
COPY . .
CMD ["sh", "-c", "ls -la && echo 'No start command defined'"]
EOF
      ;;
  esac

  # --- подставляем ENTRY ---
  ENTRY_REL="${ENTRY#$PROJECT_DIR/}"   # убираем префикс project/ (если есть)
  echo "ℹ️ ENTRY_REL resolved to: $ENTRY_REL"

  # Если ENTRY указывает на исходник .cpp — вставим команду компиляции в builder перед configure (через sed)
  if [ -n "$ENTRY_REL" ] && printf '%s' "$ENTRY_REL" | grep -qE '\.cpp$'; then
    echo "ℹ️ Detected .cpp entry -> will compile it in builder and use /usr/local/bin/ci_entry as runtime entry"
    # вставим строку после строки "# ensure possible dirs exist so COPY from builder won't fail"
    # добавим команду: RUN mkdir -p build && g++ -std=c++17 "<ENTRY_REL>" -o build/ci_entry || true
    # в Dockerfile, заменяем маркер ${ENTRY} позже на /usr/local/bin/ci_entry
    # используем sed с учётом платформы
    compile_cmd="RUN mkdir -p build && g++ -std=c++17 \"$ENTRY_REL\" -o build/ci_entry || true"
    if sed --version >/dev/null 2>&1; then
      # GNU sed
      sed -i "/# ensure possible dirs exist so COPY from builder won't fail/a $compile_cmd" "$DOCKERFILE_PATH"
    else
      # BSD/mac sed (rare on CI but included for portability)
      sed -i '' "/# ensure possible dirs exist so COPY from builder won't fail/a\\
$compile_cmd
" "$DOCKERFILE_PATH"
    fi

    # В рантайме мы копируем /src/build -> /tmp/build и затем cp в /usr/local/bin.
    # поэтому укажем ENTRY_rel как /usr/local/bin/ci_entry
    ENTRY_REL="/usr/local/bin/ci_entry"
  fi

  # Подставляем ENTRY_REL в Dockerfile
  if [ -n "$ENTRY_REL" ]; then
    if sed --version >/dev/null 2>&1; then
      sed -i "s|\${ENTRY}|$ENTRY_REL|g" "$DOCKERFILE_PATH"
    else
      sed -i '' "s|\${ENTRY}|$ENTRY_REL|g" "$DOCKERFILE_PATH"
    fi
  fi
fi

# Build arguments: platform, tag, push/load
PLATFORMS="$TARGETS"

if [ "$BUILDX" = "true" ]; then
  docker buildx inspect >/dev/null 2>&1 || docker buildx create --use
  if [ "$PUSH" = "true" ]; then
    docker buildx build --platform "$PLATFORMS" -t "$IMAGE_NAME" --push -f "$DOCKERFILE_PATH" "$PROJECT_DIR"
  else
    if [ "$LOAD_LOCAL" = "true" ]; then
      docker buildx build --platform "$PLATFORMS" -t "$IMAGE_NAME" --load -f "$DOCKERFILE_PATH" "$PROJECT_DIR"
    else
      docker buildx build --platform "$PLATFORMS" -t "$IMAGE_NAME" -f "$DOCKERFILE_PATH" "$PROJECT_DIR"
    fi
  fi
else
  docker build -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" "$PROJECT_DIR"
  if [ "$PUSH" = "true" ]; then
    docker push "$IMAGE_NAME"
  fi
fi

# Удаляем временный Dockerfile, если генерили
if [ "$DOCKERFILE_PATH" = "$PROJECT_DIR/Dockerfile.ci" ]; then
  rm -f "$DOCKERFILE_PATH"
fi

echo "✅ Done."